(function(){"use strict";
const $=id=>document.getElementById(id),eur=v=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(v),num=v=>new Intl.NumberFormat("de-DE",{maximumFractionDigits:2}).format(v),esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const OFFICIAL={
 name:"BKM Preislisten Stand 01.01.2017",date:"2017-01-01",
 wallSurcharges:{"24":0,"30":10,"36":15,"42":20,"48":25,"60":35},
 hs:{tiers:{"3":890,"4":1170,"5":1440,"6":1700,"7":1950,"8":2190,"9":2420,"10":2640,"11":2850,"12":3050},threshold:12,additional:195},
 fs:{tiers:{"2":1580,"3":2360,"4":3130,"5":3890,"6":4640,"7":5380,"8":6100,"9":6800,"10":7500},threshold:10,additional:690},
 resin:{tiers:{"2":1180,"3":1750,"4":2310,"5":2860,"6":3400,"7":3930,"8":4450,"9":4960,"10":5460},threshold:10,additional:495}
};
const DEFAULT_ADMIN={priceList:OFFICIAL,materialEK:30,personnelCost:35,workers:1,drill:60,fill:30,close:40,setupHours:1,reservePct:10,smallCost:200,fixedCost:250,resinCost:0,areaCost:0,wallSoleCost:0,wallSolePrice:300,extras:[
{name:"Baustelleneinrichtung inkl. An- und Abfahrt",unit:"pauschal",gross:320.11,cost:269,active:true},
{name:"Heizkörper demontieren und montieren",unit:"Stück",gross:150,cost:40,active:true},
{name:"Bauschutt entsorgen",unit:"pauschal",gross:350,cost:80,active:true},
{name:"Vorarbeiten / Freilegen",unit:"Stunden",gross:101.15,cost:35,active:true}
],workerUrl:"https://mainabdichter-lexoffice.cmww7htry5.workers.dev",appSecret:""};
let admin=load("v7_admin",DEFAULT_ADMIN),visit=load("v7_visit",newVisit()),discount=load("v7_discount",{type:"none",custom:0,specialType:"none",specialValue:0,specialLabel:"Sonderaktion"});
function clone(o){return JSON.parse(JSON.stringify(o))}function load(k,d){try{return{...clone(d),...JSON.parse(localStorage.getItem(k)||"{}")}}catch{return clone(d)}}function newArea(name="Vorderwand"){return{name,wallMaterial:"HBL / Hohlblockstein",wallMaterialOther:"",wallThickness:30,wallType:"Außenwand",earthContact:"erdberührt",wallCover:"Putz",access:"normal",notes:"",measurements:[{device:"Gann Hydromette Compact B",value:"",unit:"Digits",height:"",location:"",note:""}],measures:[{type:"Horizontalsperre",length:0,width:0,height:0,wall:30,spacing:0.25,note:""}],photos:[]}}function newVisit(){return{customer:{salutation:"",firstName:"",lastName:"",phone:"",email:"",company:"",street:"",zip:"",city:"",objectAddress:"",pipedriveId:""},building:{yearBuilt:"",buildingType:"freistehendes Einfamilienhaus",floor:"Keller",roomUse:"Kellerraum",foundationType:"Streifenfundament",roomHeight:"",floorCover:"",roomTemp:"",humidity:"",surfaceTemp:"",dewPoint:""},damageDescription:"",customerDescription:"",areas:[newArea()],extraQuantities:{}}}
function save(){localStorage.setItem("v7_admin",JSON.stringify(admin));localStorage.setItem("v7_visit",JSON.stringify(visit));localStorage.setItem("v7_discount",JSON.stringify(discount))}
document.querySelectorAll(".main-nav button").forEach(b=>b.onclick=()=>show(b.dataset.page));function show(id){document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll(".main-nav button").forEach(b=>b.classList.toggle("active",b.dataset.page===id));$(id).classList.add("active");if(id==="offer")calculate();if(id==="admin")renderAdmin()}
$("startVisit").onclick=()=>{visit=newVisit();save();renderVisit();show("visit")};$("continueVisit").onclick=()=>{renderVisit();show("visit")};$("openOffer").onclick=()=>show("offer");$("openAdmin").onclick=()=>show("admin");$("loadPipedrive").onclick=()=>pipedriveDialog();$("clearVisit").onclick=()=>{if(confirm("Aktuelle Besichtigung wirklich löschen?")){visit=newVisit();save();renderVisit()}};$("saveVisit").onclick=()=>{collectVisit();save();status("offerStatus","Besichtigung gespeichert.",true)};$("toOffer").onclick=()=>{collectVisit();save();show("offer")};
const customerFields=["salutation","firstName","lastName","phone","email","company","street","zip","city","objectAddress","pipedriveId"],buildingFields=["yearBuilt","buildingType","floor","roomUse","foundationType","roomHeight","floorCover","roomTemp","humidity","surfaceTemp","dewPoint"];
function renderVisit(){customerFields.forEach(k=>$(k).value=visit.customer[k]||"");buildingFields.forEach(k=>$(k).value=visit.building[k]||"");$("damageDescription").value=visit.damageDescription||"";$("customerDescription").value=visit.customerDescription||"";renderAreas();renderWorkExtras();bindSpeech();updateDew()}
function collectVisit(){customerFields.forEach(k=>visit.customer[k]=$(k).value);buildingFields.forEach(k=>visit.building[k]=$(k).value);visit.damageDescription=$("damageDescription").value;visit.customerDescription=$("customerDescription").value}
["roomTemp","humidity"].forEach(id=>$(id).oninput=updateDew);function updateDew(){const t=+$("roomTemp").value,rh=+$("humidity").value;if(Number.isFinite(t)&&rh>0){const a=17.62,b=243.12,g=Math.log(rh/100)+a*t/(b+t);$("dewPoint").value=(b*g/(a-g)).toFixed(1)}else $("dewPoint").value=""}
function renderAreas(){const box=$("areaList");box.innerHTML="";visit.areas.forEach((a,ai)=>{const d=document.createElement("div");d.className="area-card";d.innerHTML=`<div class="area-head"><h3>${ai+1}. ${esc(a.name)}</h3><button class="danger" data-adel="${ai}">Löschen</button></div><div class="grid"><div><label>Bezeichnung</label><input data-ai="${ai}" data-af="name" value="${esc(a.name)}"></div><div><label>Wandmaterial</label><select data-ai="${ai}" data-af="wallMaterial">${["HBL / Hohlblockstein","Ziegel","Kalksandstein","Beton","Naturstein","Mischmauerwerk","Sonstiges","Unbekannt"].map(v=>`<option ${a.wallMaterial===v?"selected":""}>${v}</option>`).join("")}</select></div><div><label>Abweichendes Material</label><input data-ai="${ai}" data-af="wallMaterialOther" value="${esc(a.wallMaterialOther)}"></div><div><label>Wandstärke</label><select data-ai="${ai}" data-af="wallThickness">${[24,30,36,42,48,60].map(v=>`<option value="${v}" ${+a.wallThickness===v?"selected":""}>${v} cm</option>`).join("")}</select></div><div><label>Wandart</label><select data-ai="${ai}" data-af="wallType"><option ${a.wallType==="Außenwand"?"selected":""}>Außenwand</option><option ${a.wallType==="Innenwand"?"selected":""}>Innenwand</option></select></div><div><label>Erdkontakt</label><select data-ai="${ai}" data-af="earthContact"><option ${a.earthContact==="erdberührt"?"selected":""}>erdberührt</option><option ${a.earthContact==="nicht erdberührt"?"selected":""}>nicht erdberührt</option></select></div><div><label>Wandbelag</label><select data-ai="${ai}" data-af="wallCover">${["Putz","Farbe","Tapete","Fliesen","Unbekannt","Sonstiges"].map(v=>`<option ${a.wallCover===v?"selected":""}>${v}</option>`).join("")}</select></div><div><label>Zugänglichkeit</label><select data-ai="${ai}" data-af="access"><option ${a.access==="normal"?"selected":""}>normal</option><option ${a.access==="eingeschränkt"?"selected":""}>eingeschränkt</option><option ${a.access==="schwierig"?"selected":""}>schwierig</option></select></div></div><label>Notizen</label><div class="speech-row"><textarea id="areaNote${ai}" data-ai="${ai}" data-af="notes">${esc(a.notes)}</textarea><button class="speech" data-speech-target="areaNote${ai}">🎤</button></div><h3>Messpunkte</h3><div id="measurements${ai}"></div><button class="secondary" data-addmeasurement="${ai}">+ Messpunkt</button><h3>Maßnahmen</h3><div id="measures${ai}"></div><button class="secondary" data-addmeasure="${ai}">+ Maßnahme</button><h3>Fotos</h3><input type="file" accept="image/*" capture="environment" multiple data-photo="${ai}"><div id="photos${ai}" class="photo-grid"></div>`;box.appendChild(d);renderMeasurements(ai);renderMeasures(ai);renderPhotos(ai)});
box.querySelectorAll("[data-af]").forEach(x=>x.oninput=()=>{visit.areas[+x.dataset.ai][x.dataset.af]=x.value;if(x.dataset.af==="wallThickness")visit.areas[+x.dataset.ai].measures.forEach(m=>m.wall=+x.value);save()});box.querySelectorAll("[data-adel]").forEach(x=>x.onclick=()=>{visit.areas.splice(+x.dataset.adel,1);renderAreas();save()});box.querySelectorAll("[data-addmeasurement]").forEach(x=>x.onclick=()=>{visit.areas[+x.dataset.addmeasurement].measurements.push({device:"Gann Hydromette Compact B",value:"",unit:"Digits",height:"",location:"",note:""});renderAreas();save()});box.querySelectorAll("[data-addmeasure]").forEach(x=>x.onclick=()=>{const a=visit.areas[+x.dataset.addmeasure];a.measures.push({type:"Horizontalsperre",length:0,width:0,height:0,wall:+a.wallThickness,spacing:0.25,note:""});renderAreas();save()});box.querySelectorAll("[data-photo]").forEach(x=>x.onchange=e=>{const ai=+x.dataset.photo;[...e.target.files].forEach(f=>{const r=new FileReader();r.onload=v=>{visit.areas[ai].photos.push({src:v.target.result,caption:"",show:true});renderAreas();save()};r.readAsDataURL(f)});e.target.value=""});bindSpeech()}
function renderMeasurements(ai){const box=$("measurements"+ai);box.innerHTML="";visit.areas[ai].measurements.forEach((m,mi)=>{box.innerHTML+=`<div class="sub-card"><div class="item-grid"><div class="wide"><label>Gerät</label><input data-mi="${ai}-${mi}" data-mf="device" value="${esc(m.device)}"></div><div><label>Wert</label><input data-mi="${ai}-${mi}" data-mf="value" value="${esc(m.value)}"></div><div><label>Einheit</label><input data-mi="${ai}-${mi}" data-mf="unit" value="${esc(m.unit)}"></div><div><label>Höhe cm</label><input data-mi="${ai}-${mi}" data-mf="height" value="${esc(m.height)}"></div><div><label>Position</label><input data-mi="${ai}-${mi}" data-mf="location" value="${esc(m.location)}"></div><div class="wide"><label>Bemerkung</label><input data-mi="${ai}-${mi}" data-mf="note" value="${esc(m.note)}"></div><button class="danger" data-mdel="${ai}-${mi}">Löschen</button></div></div>`});box.querySelectorAll("[data-mf]").forEach(x=>x.oninput=()=>{const [a,m]=x.dataset.mi.split("-").map(Number);visit.areas[a].measurements[m][x.dataset.mf]=x.value;save()});box.querySelectorAll("[data-mdel]").forEach(x=>x.onclick=()=>{const [a,m]=x.dataset.mdel.split("-").map(Number);visit.areas[a].measurements.splice(m,1);renderAreas();save()})}
function renderMeasures(ai){const box=$("measures"+ai);box.innerHTML="";visit.areas[ai].measures.forEach((m,mi)=>{const area=m.type==="Flächensperre";box.innerHTML+=`<div class="sub-card"><div class="item-grid"><div class="wide"><label>Maßnahme</label><select data-x="${ai}-${mi}" data-xf="type">${["Horizontalsperre","Flächensperre","Harzverpressung","Wand-Sohlen-Anschluss"].map(v=>`<option ${m.type===v?"selected":""}>${v}</option>`).join("")}</select></div><div><label>Wandstärke</label><select data-x="${ai}-${mi}" data-xf="wall">${[24,30,36,42,48,60].map(v=>`<option value="${v}" ${+m.wall===v?"selected":""}>${v} cm</option>`).join("")}</select></div>${area?`<div><label>Breite m</label><input data-x="${ai}-${mi}" data-xf="width" value="${m.width}"></div><div><label>Höhe m</label><input data-x="${ai}-${mi}" data-xf="height" value="${m.height}"></div>`:`<div><label>Länge lfm</label><input data-x="${ai}-${mi}" data-xf="length" value="${m.length}"></div>`}${["Horizontalsperre","Flächensperre","Wand-Sohlen-Anschluss"].includes(m.type)?`<div><label>horizontaler Abstand</label><select data-x="${ai}-${mi}" data-xf="spacing"><option value="0.125" ${+m.spacing===.125?"selected":""}>12,5 cm</option><option value="0.25" ${+m.spacing===.25?"selected":""}>25 cm</option></select></div>`:""}<div class="wide"><label>Notiz</label><input data-x="${ai}-${mi}" data-xf="note" value="${esc(m.note)}"></div><button class="danger" data-xdel="${ai}-${mi}">Löschen</button></div></div>`});box.querySelectorAll("[data-xf]").forEach(x=>x.oninput=()=>{const [a,m]=x.dataset.x.split("-").map(Number);visit.areas[a].measures[m][x.dataset.xf]=x.value;if(x.dataset.xf==="type")renderAreas();save()});box.querySelectorAll("[data-xdel]").forEach(x=>x.onclick=()=>{const [a,m]=x.dataset.xdel.split("-").map(Number);visit.areas[a].measures.splice(m,1);renderAreas();save()})}
function renderPhotos(ai){const box=$("photos"+ai);box.innerHTML="";visit.areas[ai].photos.forEach((p,pi)=>{box.innerHTML+=`<div class="photo-card"><img src="${p.src}"><input data-p="${ai}-${pi}" data-pf="caption" value="${esc(p.caption)}" placeholder="Beschreibung"><label><input type="checkbox" data-ps="${ai}-${pi}" ${p.show?"checked":""}> Kunden-PDF</label><button class="danger" data-pdel="${ai}-${pi}">Löschen</button></div>`});box.querySelectorAll("[data-pf]").forEach(x=>x.oninput=()=>{const [a,p]=x.dataset.p.split("-").map(Number);visit.areas[a].photos[p][x.dataset.pf]=x.value;save()});box.querySelectorAll("[data-ps]").forEach(x=>x.onchange=()=>{const [a,p]=x.dataset.ps.split("-").map(Number);visit.areas[a].photos[p].show=x.checked;save()});box.querySelectorAll("[data-pdel]").forEach(x=>x.onclick=()=>{const [a,p]=x.dataset.pdel.split("-").map(Number);visit.areas[a].photos.splice(p,1);renderAreas();save()})}
$("addArea").onclick=()=>{visit.areas.push(newArea("Neuer Schadensbereich"));renderAreas();save()};
function renderWorkExtras(){const box=$("workExtras");box.innerHTML="";admin.extras.filter(e=>e.active).forEach((e,i)=>{const qty=visit.extraQuantities[e.name]||0;box.innerHTML+=`<div class="catalog-row"><div class="grid"><div><strong>${esc(e.name)}</strong><small>${esc(e.unit)}</small></div><div><label>Menge</label><input type="number" step=".01" data-workextra="${esc(e.name)}" value="${qty}"></div></div></div>`});box.querySelectorAll("[data-workextra]").forEach(x=>x.oninput=()=>{visit.extraQuantities[x.dataset.workextra]=+x.value||0;save()})}
function priceTier(cfg,amount){const keys=Object.keys(cfg.tiers).map(Number).sort((a,b)=>a-b);for(const k of keys)if(amount<=k)return cfg.tiers[k];return cfg.tiers[cfg.threshold]+(amount-cfg.threshold)*cfg.additional}
function surcharge(price,wall){return price*(1+(admin.priceList.wallSurcharges[String(wall)]||0)/100)}
function calcMeasure(m){const wall=+m.wall||24,spacing=+m.spacing||.25,reserve=admin.reservePct/100;let holes=0,liters=0,hours=0,gross=0,material=0,label="",unit=0,unitLabel="lfm";
if(m.type==="Horizontalsperre"){unit=+m.length||0;holes=Math.ceil(unit/spacing);liters=holes*wall*14/1000;gross=surcharge(priceTier(admin.priceList.hs,unit),wall);label=`${num(unit)} lfm`;material=Math.ceil(liters*(1+reserve))*admin.materialEK}
if(m.type==="Flächensperre"){const width=+m.width||0,height=+m.height||0;unit=width*height;unitLabel="m²";const perRow=Math.ceil(width/spacing),rows=Math.ceil(height/.25);holes=perRow*rows;liters=perRow*wall*14/1000+Math.max(0,rows-1)*perRow*wall*10/1000;gross=surcharge(priceTier(admin.priceList.fs,unit),wall);label=`${num(width)} × ${num(height)} m = ${num(unit)} m²`;material=Math.ceil(liters*(1+reserve))*admin.materialEK+unit*admin.areaCost}
if(m.type==="Harzverpressung"){unit=+m.length||0;gross=surcharge(priceTier(admin.priceList.resin,unit),wall);label=`${num(unit)} lfm`;material=unit*admin.resinCost}
if(m.type==="Wand-Sohlen-Anschluss"){unit=+m.length||0;holes=Math.ceil(unit/spacing);liters=holes*wall*14/1000;gross=unit*admin.wallSolePrice+surcharge(priceTier(admin.priceList.hs,unit),wall);label=`${num(unit)} lfm inkl. Horizontalsperre`;material=Math.ceil(liters*(1+reserve))*admin.materialEK+unit*admin.wallSoleCost}
if(holes)hours=holes/admin.drill+holes/admin.fill+holes/admin.close+admin.setupHours;const personnel=hours*admin.personnelCost*admin.workers;return{gross,holes,liters,reserveLiters:Math.ceil(liters*(1+reserve)),hours,material,personnel,label,unit,unitLabel,unitPrice:unit?gross/unit:0}}
function pricing(normal){const pct=discount.type==="custom"?+discount.custom||0:discount.type==="none"?0:+discount.type||0;let special=0;if(discount.specialType==="percent")special=normal*(+discount.specialValue||0)/100;if(discount.specialType==="amount")special=+discount.specialValue||0;special=Math.max(0,Math.min(normal,special));const offer=normal-special;return{pct,special,offer,skonto:offer*(1-pct/100)}}
function calculate(){collectVisit();let measureGross=0,material=0,personnel=0,hours=0,hz=0,extraGross=0,extraCost=0;$("internalAreas").innerHTML="";$("offerMeasures").innerHTML="";$("offerExtras").innerHTML="";$("offerPhotos").innerHTML="";
visit.areas.forEach(a=>{a.measures.forEach(m=>{const r=calcMeasure(m);measureGross+=r.gross;material+=r.material;personnel+=r.personnel;hours+=r.hours;hz+=r.reserveLiters;$("internalAreas").innerHTML+=`<div class="result"><strong>${esc(a.name)} - ${esc(m.type)}</strong><div class="metric"><span>Umfang</span><strong>${r.label}</strong></div><div class="metric"><span>Bohrlöcher</span><strong>${r.holes}</strong></div><div class="metric"><span>Material inkl. Reserve</span><strong>${r.reserveLiters} l</strong></div><div class="metric"><span>Arbeitszeit</span><strong>${num(r.hours)} Std.</strong></div><div class="metric"><span>Preis je ${r.unitLabel}</span><strong>${eur(r.unitPrice)}</strong></div><div class="metric"><span>Preis brutto</span><strong>${eur(r.gross)}</strong></div></div>`;$("offerMeasures").innerHTML+=`<div class="metric"><span>${esc(a.name)} - ${esc(m.type)}</span><strong>${r.label}</strong></div>`});a.photos.filter(p=>p.show).forEach(p=>$("offerPhotos").innerHTML+=`<div class="photo-card"><img src="${p.src}"><strong>${esc(a.name)}</strong>${p.caption?`<p>${esc(p.caption)}</p>`:""}</div>`)});
admin.extras.filter(e=>e.active).forEach(e=>{const qty=visit.extraQuantities[e.name]||0;if(qty>0){extraGross+=qty*e.gross;extraCost+=qty*e.cost;$("offerExtras").innerHTML+=`<div class="metric"><span>${esc(e.name)} (${num(qty)} ${esc(e.unit)})</span><strong>${eur(qty*e.gross)}</strong></div>`}});
const normal=measureGross+extraGross,p=pricing(normal),self=material+personnel+extraCost+admin.smallCost+admin.fixedCost,netOffer=p.offer/1.19;$("totalHz").textContent=hz+" l";$("totalHours").textContent=num(hours)+" Std.";$("materialCost").textContent=eur(material);$("personnelCost").textContent=eur(personnel);$("selfCost").textContent=eur(self);$("margin").textContent=eur(netOffer-self);$("offerCustomer").textContent=[visit.customer.salutation,visit.customer.firstName,visit.customer.lastName].filter(Boolean).join(" ")||"-";$("offerAddress").textContent=visit.customer.objectAddress||[visit.customer.street,visit.customer.zip,visit.customer.city].filter(Boolean).join(", ")||"-";$("offerDescription").textContent=visit.customerDescription||"-";$("normalPrice").textContent=eur(normal);$("specialRowLabel").textContent=discount.specialLabel||"Sonderaktion";$("specialAmount").textContent="− "+eur(p.special);$("normalPriceRow").classList.toggle("hidden",p.special<=0);$("specialRow").classList.toggle("hidden",p.special<=0);$("offerPrice").textContent=eur(p.offer);$("skontoText").textContent=`${num(p.pct)} % Skonto bei Zahlung innerhalb von 3 Werktagen`;$("skontoPrice").textContent=eur(p.skonto);$("skontoRow").classList.toggle("hidden",p.pct<=0);$("dashboardOffer").textContent=eur(p.offer);$("dashboardCustomer").textContent=[visit.customer.firstName,visit.customer.lastName].filter(Boolean).join(" ")||"-";$("dashboardPriceList").textContent=admin.priceList.name}
["discountType","discountCustom","specialType","specialValue","specialLabel"].forEach(id=>$(id).oninput=()=>{discount={type:$("discountType").value,custom:+$("discountCustom").value||0,specialType:$("specialType").value,specialValue:+$("specialValue").value||0,specialLabel:$("specialLabel").value};save();calculate()});$("toggleInternal").onclick=()=>$("internalCalculation").classList.toggle("hidden");
function renderAdmin(){admin.priceList=admin.priceList||clone(OFFICIAL);$("priceListName").value=admin.priceList.name;$("priceListDate").value=admin.priceList.date;$("adminMaterialEK").value=admin.materialEK;$("adminPersonnelCost").value=admin.personnelCost;$("adminWorkers").value=admin.workers;$("adminDrill").value=admin.drill;$("adminFill").value=admin.fill;$("adminClose").value=admin.close;$("adminSetupHours").value=admin.setupHours;$("adminReserve").value=admin.reservePct;$("adminSmallCost").value=admin.smallCost;$("adminFixedCost").value=admin.fixedCost;$("adminResinCost").value=admin.resinCost;$("adminAreaCost").value=admin.areaCost;$("adminWallSoleCost").value=admin.wallSoleCost;$("adminWallSolePrice").value=admin.wallSolePrice;$("workerUrl").value=admin.workerUrl;$("appSecret").value=admin.appSecret;renderObjectEditor("wallSurcharges",admin.priceList.wallSurcharges,"cm","%");renderPriceEditor("hsPrices",admin.priceList.hs,"lfm");renderPriceEditor("fsPrices",admin.priceList.fs,"m²");renderPriceEditor("resinPrices",admin.priceList.resin,"lfm");renderAdminExtras()}
function renderObjectEditor(id,obj,keySuffix,valueSuffix){const b=$(id);b.innerHTML="";Object.entries(obj).forEach(([k,v])=>b.innerHTML+=`<div class="catalog-row"><div class="grid"><div><label>${k} ${keySuffix}</label><input value="${v}" data-obj="${id}" data-key="${k}"></div><div><label>Aufschlag ${valueSuffix}</label><input value="${v}" data-surcharge="${k}"></div></div></div>`);b.querySelectorAll("[data-surcharge]").forEach(x=>x.oninput=()=>admin.priceList.wallSurcharges[x.dataset.surcharge]=+x.value||0)}
function renderPriceEditor(id,cfg,unit){const b=$(id);b.innerHTML="";Object.entries(cfg.tiers).forEach(([k,v])=>b.innerHTML+=`<div class="catalog-row"><div class="grid"><div><label>bis ${k} ${unit}</label><input value="${v}" data-tier="${id}-${k}"></div><div><label>brutto €</label><input value="${v}" data-price="${k}"></div></div></div>`);b.innerHTML+=`<div class="catalog-row"><div class="grid"><div><label>ab ${cfg.threshold} ${unit}: je weitere Einheit</label><input value="${cfg.additional}" data-additional="${id}"></div></div></div>`;b.querySelectorAll("[data-price]").forEach(x=>x.oninput=()=>cfg.tiers[x.dataset.price]=+x.value||0);b.querySelector("[data-additional]").oninput=x=>cfg.additional=+x.target.value||0}
function renderAdminExtras(){const b=$("adminExtras");b.innerHTML="";admin.extras.forEach((e,i)=>b.innerHTML+=`<div class="catalog-row"><div class="item-grid"><div class="wide"><label>Leistung</label><input data-ae="${i}" data-aef="name" value="${esc(e.name)}"></div><div><label>Einheit</label><input data-ae="${i}" data-aef="unit" value="${esc(e.unit)}"></div><div><label>VK brutto</label><input data-ae="${i}" data-aef="gross" value="${e.gross}"></div><div><label>EK netto</label><input data-ae="${i}" data-aef="cost" value="${e.cost}"></div><label><input type="checkbox" data-aactive="${i}" ${e.active?"checked":""}> aktiv</label><button class="danger" data-aedel="${i}">Löschen</button></div></div>`);b.querySelectorAll("[data-aef]").forEach(x=>x.oninput=()=>admin.extras[+x.dataset.ae][x.dataset.aef]=x.value);b.querySelectorAll("[data-aactive]").forEach(x=>x.onchange=()=>admin.extras[+x.dataset.aactive].active=x.checked);b.querySelectorAll("[data-aedel]").forEach(x=>x.onclick=()=>{admin.extras.splice(+x.dataset.aedel,1);renderAdminExtras()})}
$("addAdminExtra").onclick=()=>{admin.extras.push({name:"Neue Leistung",unit:"pauschal",gross:0,cost:0,active:true});renderAdminExtras()};
$("saveAdmin").onclick=()=>{admin.priceList.name=$("priceListName").value;admin.priceList.date=$("priceListDate").value;["materialEK","personnelCost","workers","drill","fill","close","setupHours","reservePct","smallCost","fixedCost","resinCost","areaCost","wallSoleCost","wallSolePrice"].forEach(k=>admin[k]=+$( "admin"+({materialEK:"MaterialEK",personnelCost:"PersonnelCost",workers:"Workers",drill:"Drill",fill:"Fill",close:"Close",setupHours:"SetupHours",reservePct:"Reserve",smallCost:"SmallCost",fixedCost:"FixedCost",resinCost:"ResinCost",areaCost:"AreaCost",wallSoleCost:"WallSoleCost",wallSolePrice:"WallSolePrice"}[k])).value||0);admin.workerUrl=$("workerUrl").value.trim().replace(/\/$/,"");admin.appSecret=$("appSecret").value;save();renderWorkExtras();status("adminStatus","Einstellungen dauerhaft gespeichert.",true);calculate()};
$("resetAdmin").onclick=()=>{if(confirm("BKM-Standardpreise und Standardwerte laden?")){admin=clone(DEFAULT_ADMIN);save();renderAdmin();status("adminStatus","Standardwerte geladen.",true)}};
function bindSpeech(){document.querySelectorAll("[data-speech-target]").forEach(b=>b.onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR)return alert("Nutze die Mikrofontaste der iPhone-Tastatur.");const r=new SR();r.lang="de-DE";r.onresult=e=>{$(b.dataset.speechTarget).value+=($(b.dataset.speechTarget).value?" ":"")+e.results[0][0].transcript};r.start()})}
function cfg(){return{url:admin.workerUrl,secret:admin.appSecret}}async function api(path,opt={}){const c=cfg(),r=await fetch(c.url+path,{...opt,headers:{...(opt.headers||{}),"X-App-Secret":c.secret}}),d=await r.json();if(!r.ok)throw new Error(d.error||"Fehler");return d}
async function pipedriveDialog(){const term=prompt("Kunde in Pipedrive suchen:");if(!term)return;try{const d=await api("/pipedrive/persons/search?term="+encodeURIComponent(term));if(!d.people.length)return alert("Kein Treffer.");const labels=d.people.map((p,i)=>`${i+1}: ${p.name} ${p.email||""}`).join("\n");const nr=+prompt(labels+"\n\nNummer auswählen:");const selected=d.people[nr-1];if(!selected)return;const detail=await api("/pipedrive/persons/"+selected.id),p=detail.person;visit.customer={...visit.customer,pipedriveId:p.id||"",firstName:p.firstName||"",lastName:p.lastName||p.name||"",email:p.email||"",phone:p.phone||"",street:p.street||"",zip:p.zip||"",city:p.city||"",objectAddress:p.objectAddress||""};save();renderVisit()}catch(e){alert(e.message)}}
$("sendLexware").onclick=async()=>{try{await api("/contacts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({salutation:visit.customer.salutation,firstName:visit.customer.firstName,lastName:visit.customer.lastName,street:visit.customer.street,zip:visit.customer.zip,city:visit.customer.city,email:visit.customer.email,phone:visit.customer.phone,note:"Pipedrive-ID: "+visit.customer.pipedriveId})});status("offerStatus","Kunde an Lexware übertragen.",true)}catch(e){status("offerStatus",e.message,false)}};
function reportRow(l,v){return v?`<tr><th>${esc(l)}</th><td>${esc(v)}</td></tr>`:""}function buildReport(){calculate();let h=`<div class="report-section"><h2>Kunde und Objekt</h2><table class="report-table">${reportRow("Kunde",[visit.customer.salutation,visit.customer.firstName,visit.customer.lastName].filter(Boolean).join(" "))}${reportRow("Objekt",visit.customer.objectAddress||[visit.customer.street,visit.customer.zip,visit.customer.city].filter(Boolean).join(", "))}${reportRow("Baujahr",visit.building.yearBuilt)}${reportRow("Bauart",visit.building.buildingType)}${reportRow("Geschoss",visit.building.floor)}${reportRow("Fundamentart",visit.building.foundationType)}${reportRow("Raumtemperatur",visit.building.roomTemp?visit.building.roomTemp+" °C":"")}${reportRow("Luftfeuchtigkeit",visit.building.humidity?visit.building.humidity+" %":"")}${reportRow("Oberflächentemperatur",visit.building.surfaceTemp?visit.building.surfaceTemp+" °C":"")}${reportRow("Taupunkt",visit.building.dewPoint?visit.building.dewPoint+" °C":"")}</table></div><div class="report-section"><h2>Schadensbild</h2><p>${esc(visit.damageDescription)}</p><h2>Empfehlung</h2><p>${esc(visit.customerDescription)}</p></div>`;visit.areas.forEach((a,i)=>{h+=`<div class="report-section"><h2>${i+1}. ${esc(a.name)}</h2><table class="report-table">${reportRow("Wandmaterial",a.wallMaterialOther||a.wallMaterial)}${reportRow("Wandstärke",a.wallThickness+" cm")}${reportRow("Erdkontakt",a.earthContact)}${reportRow("Wandbelag",a.wallCover)}${reportRow("Notizen",a.notes)}</table><h3>Messwerte</h3><table class="report-table"><tr><th>Gerät</th><th>Wert</th><th>Höhe</th><th>Position</th><th>Bemerkung</th></tr>${a.measurements.map(m=>`<tr><td>${esc(m.device)}</td><td>${esc(m.value+" "+m.unit)}</td><td>${esc(m.height)}</td><td>${esc(m.location)}</td><td>${esc(m.note)}</td></tr>`).join("")}</table><h3>Maßnahmen</h3><table class="report-table">${a.measures.map(m=>{const r=calcMeasure(m);return`<tr><th>${esc(m.type)}</th><td>${r.label}</td></tr>`}).join("")}</table><div class="photo-grid">${a.photos.filter(p=>p.show).map(p=>`<div class="photo-card"><img src="${p.src}"><p>${esc(p.caption)}</p></div>`).join("")}</div></div>`});$("reportContent").innerHTML=h}
function printMode(mode){document.body.classList.add(mode);window.print();setTimeout(()=>document.body.classList.remove(mode),400)}$("printCustomerPdf").onclick=()=>{calculate();printMode("print-offer")};$("printReportPdf").onclick=()=>{buildReport();printMode("print-report")};
function status(id,msg,ok){const s=$(id);s.className="status "+(ok?"ok":"err");s.textContent=msg}
$("discountType").value=discount.type;$("discountCustom").value=discount.custom;$("specialType").value=discount.specialType;$("specialValue").value=discount.specialValue;$("specialLabel").value=discount.specialLabel;
renderVisit();renderAdmin();calculate();show("dashboard");
})();