const JSPDF_URL="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js";
let loader=null;
function loadScript(url){return new Promise((resolve,reject)=>{if(window.jspdf){resolve();return;}const old=document.querySelector(`script[src="${url}"]`);if(old){old.addEventListener("load",resolve,{once:true});return;}const s=document.createElement("script");s.src=url;s.async=true;s.onload=resolve;s.onerror=()=>reject(new Error("PDF-Modul konnte nicht geladen werden."));document.head.appendChild(s);});}
async function jsPDF(){if(!window.jspdf){loader ||= loadScript(JSPDF_URL);await loader;}return window.jspdf.jsPDF;}
function safeName(value){return String(value||"Kunde").replace(/[^a-zA-Z0-9ÄÖÜäöüß_-]+/g,"_").replace(/^_+|_+$/g,"");}
function textBlock(doc,text,x,y,width,lineHeight=5){const lines=doc.splitTextToSize(String(text||"–"),width);for(const line of lines){if(y>282){doc.addPage();y=18;}doc.text(line,x,y);y+=lineHeight;}return y;}
function heading(doc,text,y){if(y>270){doc.addPage();y=18;}doc.setFont("helvetica","bold");doc.setFontSize(13);doc.text(text,15,y);doc.setFont("helvetica","normal");doc.setFontSize(9);return y+7;}
export async function createWorksitePdf(worksite){const C=await jsPDF();const doc=new C({unit:"mm",format:"a4"});let y=18;doc.setFontSize(18);doc.setFont("helvetica","bold");doc.text("Arbeitsnachweis",15,y);y+=8;doc.setFontSize(10);doc.setFont("helvetica","normal");y=textBlock(doc,`${[worksite.customer?.salutation,worksite.customer?.firstName,worksite.customer?.lastName].filter(Boolean).join(" ")||worksite.customer?.company||"Kunde"}\n${worksite.objectAddress||""}`,15,y,180,5);y+=3;y=heading(doc,"Ausführung",y);const rows=[["Datum",worksite.date],["Mitarbeiter",worksite.employees],["Arbeitsbeginn",worksite.startTime],["Arbeitsende",worksite.endTime],["Pause",`${worksite.pauseMinutes||0} Minuten`],["Wetter",`${worksite.weather||""} ${worksite.outdoorTemp?worksite.outdoorTemp+" °C":""}`]];for(const [label,value] of rows){doc.setFont("helvetica","bold");doc.text(`${label}:`,15,y);doc.setFont("helvetica","normal");doc.text(String(value||"–"),55,y);y+=5;}for(const task of worksite.tasks||[]){y+=3;y=heading(doc,`${task.areaName} – ${task.type}`,y);const details=`Umfang: ${task.scope||"–"}\nWandstärke: ${task.wall||0} cm\nBohrlochabstand: ${task.spacing||0} m\nBohrlöcher Soll/Ist: ${task.plannedHoles||0} / ${task.actualHoles||0}\nInjektionsmenge je Bohrloch: ${Number(task.targetLitersPerHole||0).toLocaleString("de-DE",{maximumFractionDigits:3})} l\nBKM HZ 250 Pro Soll/Ist: ${task.plannedLiters||0} / ${task.actualLiters||0} l\nCharge BKM HZ 250 Pro: ${task.chargeHz||"–"}${task.type==="Wand-Sohlen-Anschluss"?`\nBKM HS Sperrmörtel Soll/Ist: ${task.plannedHsKg||0} / ${task.actualHsKg||0} kg`:""}${task.type==="Harzverpressung"?`\nPacker: ${task.packers||0}\nHarz: ${task.resinKg||0} kg`:""}\nInjektionsart: ${task.injectionType||"–"}\nVollständig ausgeführt: ${task.completed?"Ja":"Nein"}\nAusführung/Besonderheiten: ${task.note||"–"}`;y=textBlock(doc,details,15,y,180,4.7);}
y+=4;y=heading(doc,"Allgemeine Bemerkungen",y);y=textBlock(doc,worksite.generalNotes||"–",15,y,180,5);y+=5;doc.text(`Kunde/Bestätigung: ${worksite.customerSignature||"–"}`,15,y);y+=6;doc.text(`Ausführender: ${worksite.workerSignature||"–"}`,15,y);const name=safeName([worksite.customer?.firstName,worksite.customer?.lastName].filter(Boolean).join("_")||worksite.customer?.company);const filename=`${worksite.date||new Date().toISOString().slice(0,10)}_Arbeitsnachweis_${name}.pdf`;return {blob:doc.output("blob"),filename};}
export async function createVisitPdf(visit){const C=await jsPDF();const doc=new C({unit:"mm",format:"a4"});let y=18;doc.setFontSize(17);doc.setFont("helvetica","bold");doc.text("Besichtigungs- und Messprotokoll",15,y);y+=9;doc.setFontSize(9);doc.setFont("helvetica","normal");const name=[visit.customer?.salutation,visit.customer?.firstName,visit.customer?.lastName].filter(Boolean).join(" ")||visit.customer?.company||"Kunde";y=textBlock(doc,`${name}\n${visit.customer?.objectAddress||[visit.customer?.street,visit.customer?.zip,visit.customer?.city].filter(Boolean).join(", ")}\nBesichtigung: ${visit.visitDate||""} ${visit.visitStartTime||""}`,15,y,180,5);y+=4;y=heading(doc,"Schadensbild",y);y=textBlock(doc,visit.damageDescription||"–",15,y,180,5);y+=3;y=heading(doc,"Empfehlung",y);y=textBlock(doc,visit.customerRecommendation||"–",15,y,180,5);for(const area of visit.areas||[]){y+=3;y=heading(doc,area.name||"Schadensbereich",y);const ms=(area.measurements||[]).map(m=>`${m.device}: ${m.value} ${m.unit} (${m.location||""})`).join("\n");const measures=(area.measures||[]).map(m=>m.type).join(", ");y=textBlock(doc,`Wandmaterial: ${area.wallMaterialOther||area.wallMaterial||"–"}\nWandstärke: ${area.wallThickness||"–"} cm\nReferenz trocken: ${area.dryReference||"–"}\nMessungen:\n${ms||"–"}\nMaßnahmen: ${measures||"–"}`,15,y,180,4.7);}const filename=`${visit.visitDate||new Date().toISOString().slice(0,10)}_Besichtigungsprotokoll_${safeName(name)}.pdf`;return {blob:doc.output("blob"),filename};}
export function downloadBlob(blob,filename){const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
