(function(){"use strict";
const C={spacing:.25,rowSpacing:.25,fHS:14,fFS:10,reserve:.10,hzSell:98,wallSole:300,resin:495,area:690,vat:.19,hourly:85,materialEK:30,drill:60,fill:30,close:40,setupHours:1,small:200,fixed:250};
const $=id=>document.getElementById(id),eur=v=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(v),num=v=>new Intl.NumberFormat("de-DE",{maximumFractionDigits:2}).format(v),esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let areas=JSON.parse(localStorage.getItem("v6_areas")||"[]"),extras=JSON.parse(localStorage.getItem("v6_extras")||"[]");
if(!areas.length)areas=[newArea("Vorderwand")];
if(!extras.length)extras=[{name:"Baustelleneinrichtung inkl. An- und Abfahrt",qty:1,unit:"pauschal",sell:320.11,cost:269,show:true},{name:"Heizkörper demontieren und montieren",qty:0,unit:"Stück",sell:0,cost:0,show:true},{name:"Bauschutt entsorgen",qty:0,unit:"pauschal",sell:0,cost:0,show:true},{name:"Vorarbeiten / Freilegen",qty:0,unit:"Stunden",sell:0,cost:0,show:true}];
function newArea(name){return{name,wallMaterial:"HBL / Hohlblockstein",wallMaterialOther:"",wallThickness:30,wallType:"Außenwand",earthContact:"erdberührt",wallCover:"Putz",access:"normal",notes:"",measurements:[{device:"Gann Hydromette Compact B",value:"",unit:"Digits",height:"",location:"",note:""}],measures:[{type:"Horizontalsperre",length:0,width:0,height:0,wall:30,note:""}],photos:[]}}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));$(b.dataset.page).classList.add("active");b.classList.add("active")});
$("openPipedrive").onclick=()=>document.querySelector('[data-page="systems"]').click();
$("newCustomer").onclick=()=>{["salutation","firstName","lastName","phone","email","company","street","zip","city","objectAddress","pipedriveId"].forEach(id=>$(id).value="");calc()};
["salutation","firstName","lastName","phone","email","company","street","zip","city","objectAddress","yearBuilt","buildingType","floor","roomUse","foundationType","roomHeight","floorCover","roomTemp","humidity","surfaceTemp","damageDescription","customerDescription"].forEach(id=>$(id).oninput=calc);
$("roomTemp").oninput=$("humidity").oninput=()=>{dew();calc()};
function dew(){const t=+$("roomTemp").value,rh=+$("humidity").value;if(!Number.isFinite(t)||!rh){$("dewPoint").value="";return}const a=17.62,b=243.12,g=Math.log(rh/100)+a*t/(b+t);$("dewPoint").value=(b*g/(a-g)).toFixed(1)}
function save(){localStorage.setItem("v6_areas",JSON.stringify(areas));localStorage.setItem("v6_extras",JSON.stringify(extras))}
function bindSpeech(){document.querySelectorAll("[data-speech-target]").forEach(b=>b.onclick=()=>speech(b.dataset.speechTarget))}
function speech(target){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Nutze bitte die Mikrofontaste der iPhone-Tastatur.");return}const r=new SR();r.lang="de-DE";r.onresult=e=>{const el=$(target);el.value=(el.value?el.value+" ":"")+e.results[0][0].transcript;el.dispatchEvent(new Event("input",{bubbles:true}))};r.start()}
function hs(l,w){const holes=Math.ceil((+l||0)/C.spacing);return{holes,liters:holes*(+w||0)*C.fHS/1000}}
function fs(w,h,t){const hr=Math.ceil((+w||0)/C.spacing),rows=Math.ceil((+h||0)/C.rowSpacing);return{holes:hr*rows,area:(+w||0)*(+h||0),liters:hr*(+t||0)*C.fHS/1000+Math.max(rows-1,0)*hr*(+t||0)*C.fFS/1000}}
function calcMeasure(m){let holes=0,liters=0,gross=0,label="",hours=0;if(m.type==="Horizontalsperre"){const r=hs(m.length,m.wall);holes=r.holes;liters=r.liters;gross=Math.ceil(liters*1.1)*C.hzSell*1.19;label=`${num(m.length)} lfm`}if(m.type==="Flächensperre"){const r=fs(m.width,m.height,m.wall);holes=r.holes;liters=r.liters;gross=r.area*C.area;label=`${num(m.width)} × ${num(m.height)} m = ${num(r.area)} m²`}if(m.type==="Harzverpressung"){gross=(+m.length||0)*C.resin;label=`${num(m.length)} lfm`}if(m.type==="Wand-Sohlen-Anschluss"){const r=hs(m.length,m.wall);holes=r.holes;liters=r.liters;gross=(+m.length||0)*C.wallSole+Math.ceil(liters*1.1)*C.hzSell*1.19;label=`${num(m.length)} lfm inkl. HS`}if(holes)hours=Math.ceil(holes/C.drill+holes/C.fill+holes/C.close+C.setupHours);const reserve=Math.ceil(liters*1.1),self=reserve*C.materialEK+hours*C.hourly;return{holes,liters,reserve,gross,label,hours,self}}
function renderAreas(){const box=$("areaList");box.innerHTML="";areas.forEach((a,i)=>{const d=document.createElement("div");d.className="area-card";d.innerHTML=`<div class="area-title"><h3>${i+1}. ${esc(a.name)}</h3><button class="danger" data-area-del="${i}">Löschen</button></div>
<div class="grid"><div><label>Bezeichnung</label><input data-ai="${i}" data-af="name" value="${esc(a.name)}"></div><div><label>Wandmaterial</label><select data-ai="${i}" data-af="wallMaterial">${["HBL / Hohlblockstein","Ziegel","Kalksandstein","Beton","Naturstein","Mischmauerwerk","Sonstiges","Unbekannt"].map(x=>`<option ${a.wallMaterial===x?"selected":""}>${x}</option>`).join("")}</select></div><div><label>Abweichendes Material</label><input data-ai="${i}" data-af="wallMaterialOther" value="${esc(a.wallMaterialOther)}"></div><div><label>Wandstärke cm</label><input data-ai="${i}" data-af="wallThickness" value="${a.wallThickness}"></div><div><label>Wandart</label><select data-ai="${i}" data-af="wallType"><option ${a.wallType==="Außenwand"?"selected":""}>Außenwand</option><option ${a.wallType==="Innenwand"?"selected":""}>Innenwand</option></select></div><div><label>Erdkontakt</label><select data-ai="${i}" data-af="earthContact"><option ${a.earthContact==="erdberührt"?"selected":""}>erdberührt</option><option ${a.earthContact==="nicht erdberührt"?"selected":""}>nicht erdberührt</option></select></div><div><label>Wandbelag</label><select data-ai="${i}" data-af="wallCover">${["Putz","Farbe","Tapete","Fliesen","unbekannt","Sonstiges"].map(x=>`<option ${a.wallCover===x?"selected":""}>${x}</option>`).join("")}</select></div><div><label>Zugänglichkeit</label><select data-ai="${i}" data-af="access"><option ${a.access==="normal"?"selected":""}>normal</option><option ${a.access==="eingeschränkt"?"selected":""}>eingeschränkt</option><option ${a.access==="schwierig"?"selected":""}>schwierig</option></select></div></div>
<label>Notizen</label><div class="speech-row"><textarea id="anote${i}" data-ai="${i}" data-af="notes">${esc(a.notes)}</textarea><button class="speech" data-speech-target="anote${i}">🎤</button></div>
<h4>Messpunkte</h4><div id="ams${i}"></div><button class="secondary" data-add-ms="${i}">+ Messpunkt</button>
<h4>Maßnahmen</h4><div id="ameasures${i}"></div><button class="secondary" data-add-measure="${i}">+ Maßnahme</button>
<h4>Fotos</h4><input type="file" accept="image/*" capture="environment" multiple data-photo-area="${i}"><div id="aphotos${i}" class="photo-grid"></div>`;box.appendChild(d);renderAreaMeasurements(i);renderAreaMeasures(i);renderAreaPhotos(i)});
box.querySelectorAll("[data-af]").forEach(el=>el.oninput=()=>{areas[+el.dataset.ai][el.dataset.af]=el.value;save();calc()});box.querySelectorAll("[data-area-del]").forEach(el=>el.onclick=()=>{areas.splice(+el.dataset.areaDel,1);renderAreas();save();calc()});box.querySelectorAll("[data-add-ms]").forEach(el=>el.onclick=()=>{areas[+el.dataset.addMs].measurements.push({device:"Gann Hydromette Compact B",value:"",unit:"Digits",height:"",location:"",note:""});renderAreas();save()});box.querySelectorAll("[data-add-measure]").forEach(el=>el.onclick=()=>{const a=areas[+el.dataset.addMeasure];a.measures.push({type:"Horizontalsperre",length:0,width:0,height:0,wall:a.wallThickness||30,note:""});renderAreas();save();calc()});box.querySelectorAll("[data-photo-area]").forEach(el=>el.onchange=e=>{const ai=+el.dataset.photoArea;[...e.target.files].forEach(f=>{const r=new FileReader();r.onload=x=>{areas[ai].photos.push({src:x.target.result,caption:"",show:true});renderAreas();save();calc()};r.readAsDataURL(f)});e.target.value=""});bindSpeech()}
function renderAreaMeasurements(ai){const box=$("ams"+ai);box.innerHTML="";areas[ai].measurements.forEach((m,mi)=>{box.innerHTML+=`<div class="sub-card"><div class="item-grid"><div class="wide"><label>Gerät</label><input data-ami="${ai}" data-mi="${mi}" data-mf="device" value="${esc(m.device)}"></div><div><label>Wert</label><input data-ami="${ai}" data-mi="${mi}" data-mf="value" value="${esc(m.value)}"></div><div><label>Einheit</label><input data-ami="${ai}" data-mi="${mi}" data-mf="unit" value="${esc(m.unit)}"></div><div><label>Höhe cm</label><input data-ami="${ai}" data-mi="${mi}" data-mf="height" value="${esc(m.height)}"></div><div><label>Position</label><input data-ami="${ai}" data-mi="${mi}" data-mf="location" value="${esc(m.location)}"></div><div class="wide"><label>Bemerkung</label><input data-ami="${ai}" data-mi="${mi}" data-mf="note" value="${esc(m.note)}"></div><button class="danger" data-ms-del="${ai}-${mi}">Löschen</button></div></div>`});box.querySelectorAll("[data-mf]").forEach(el=>el.oninput=()=>{areas[+el.dataset.ami].measurements[+el.dataset.mi][el.dataset.mf]=el.value;save()});box.querySelectorAll("[data-ms-del]").forEach(el=>el.onclick=()=>{const [a,m]=el.dataset.msDel.split("-").map(Number);areas[a].measurements.splice(m,1);renderAreas();save()})}
function renderAreaMeasures(ai){const box=$("ameasures"+ai);box.innerHTML="";areas[ai].measures.forEach((m,mi)=>{const ar=m.type==="Flächensperre";box.innerHTML+=`<div class="sub-card"><div class="item-grid"><div class="wide"><label>Art</label><select data-mai="${ai}" data-mmi="${mi}" data-mmf="type">${["Horizontalsperre","Flächensperre","Harzverpressung","Wand-Sohlen-Anschluss"].map(x=>`<option ${m.type===x?"selected":""}>${x}</option>`).join("")}</select></div><div><label>Wandstärke cm</label><input data-mai="${ai}" data-mmi="${mi}" data-mmf="wall" value="${m.wall}"></div>${ar?`<div><label>Breite m</label><input data-mai="${ai}" data-mmi="${mi}" data-mmf="width" value="${m.width}"></div><div><label>Höhe m</label><input data-mai="${ai}" data-mmi="${mi}" data-mmf="height" value="${m.height}"></div>`:`<div><label>Länge lfm</label><input data-mai="${ai}" data-mmi="${mi}" data-mmf="length" value="${m.length}"></div>`}<div class="wide"><label>Notiz</label><input data-mai="${ai}" data-mmi="${mi}" data-mmf="note" value="${esc(m.note)}"></div><button class="danger" data-measure-del="${ai}-${mi}">Löschen</button></div><div id="mres${ai}-${mi}"></div></div>`});box.querySelectorAll("[data-mmf]").forEach(el=>el.oninput=()=>{areas[+el.dataset.mai].measures[+el.dataset.mmi][el.dataset.mmf]=el.value;if(el.dataset.mmf==="type")renderAreas();save();calc()});box.querySelectorAll("[data-measure-del]").forEach(el=>el.onclick=()=>{const [a,m]=el.dataset.measureDel.split("-").map(Number);areas[a].measures.splice(m,1);renderAreas();save();calc()})}
function renderAreaPhotos(ai){const box=$("aphotos"+ai);box.innerHTML="";areas[ai].photos.forEach((p,pi)=>{box.innerHTML+=`<div class="photo-card"><img src="${p.src}"><input data-pai="${ai}" data-ppi="${pi}" data-ppf="caption" value="${esc(p.caption)}" placeholder="Beschreibung"><label><input type="checkbox" data-pshow="${ai}-${pi}" ${p.show?"checked":""}> Kundenansicht</label><button class="danger" data-photo-del="${ai}-${pi}">Löschen</button></div>`});box.querySelectorAll("[data-ppf]").forEach(el=>el.oninput=()=>{areas[+el.dataset.pai].photos[+el.dataset.ppi][el.dataset.ppf]=el.value;save();calc()});box.querySelectorAll("[data-pshow]").forEach(el=>el.onchange=()=>{const [a,p]=el.dataset.pshow.split("-").map(Number);areas[a].photos[p].show=el.checked;save();calc()});box.querySelectorAll("[data-photo-del]").forEach(el=>el.onclick=()=>{const [a,p]=el.dataset.photoDel.split("-").map(Number);areas[a].photos.splice(p,1);renderAreas();save();calc()})}
$("addArea").onclick=()=>{areas.push(newArea("Neuer Schadensbereich"));renderAreas();save();calc()};
function renderExtras(){const box=$("extraList");box.innerHTML="";extras.forEach((e,i)=>{box.innerHTML+=`<div class="extra-card"><div class="item-grid"><div class="wide"><label>Leistung</label><input data-ei="${i}" data-ef="name" value="${esc(e.name)}"></div><div><label>Menge</label><input data-ei="${i}" data-ef="qty" value="${e.qty}"></div><div><label>Einheit</label><input data-ei="${i}" data-ef="unit" value="${esc(e.unit)}"></div><div><label>VK brutto</label><input data-ei="${i}" data-ef="sell" value="${e.sell}"></div><div><label>EK netto</label><input data-ei="${i}" data-ef="cost" value="${e.cost}"></div><label><input type="checkbox" data-es="${i}" ${e.show?"checked":""}> Kundenansicht</label><button class="danger" data-ed="${i}">Löschen</button></div></div>`});box.querySelectorAll("[data-ef]").forEach(el=>el.oninput=()=>{extras[+el.dataset.ei][el.dataset.ef]=el.value;save();calc()});box.querySelectorAll("[data-es]").forEach(el=>el.onchange=()=>{extras[+el.dataset.es].show=el.checked;save();calc()});box.querySelectorAll("[data-ed]").forEach(el=>el.onclick=()=>{extras.splice(+el.dataset.ed,1);renderExtras();save();calc()})}
$("addExtra").onclick=()=>{extras.push({name:"",qty:1,unit:"pauschal",sell:0,cost:0,show:true});renderExtras();save();calc()};
function calc(){let mg=0,self=0,hz=0,hours=0,eg=0,ec=0;$("calcAreas").innerHTML="";$("cAreas").innerHTML="";$("cExtras").innerHTML="";$("cPhotos").innerHTML="";areas.forEach((a,ai)=>{let areaGross=0;$("calcAreas").innerHTML+=`<div class="result"><strong>${esc(a.name)}</strong><div>${esc(a.wallMaterialOther||a.wallMaterial)} · ${a.wallThickness} cm · ${esc(a.earthContact)}</div></div>`;$("cAreas").innerHTML+=`<div class="result"><strong>${esc(a.name)}</strong></div>`;a.measures.forEach((m,mi)=>{const r=calcMeasure(m);mg+=r.gross;areaGross+=r.gross;self+=r.self;hz+=r.reserve;hours+=r.hours;const el=$(`mres${ai}-${mi}`);if(el)el.textContent=`${r.label} · ${r.reserve} l · ${r.hours} Std. · ${eur(r.gross)}`;$("calcAreas").innerHTML+=`<div class="metric"><span>${esc(a.name)} – ${esc(m.type)}</span><strong>${r.label} · ${eur(r.gross)}</strong></div>`;$("cAreas").innerHTML+=`<div class="metric"><span>${esc(m.type)}</span><strong>${r.label}</strong></div>`});a.photos.filter(p=>p.show).forEach(p=>{$("cPhotos").innerHTML+=`<div class="photo-card"><img src="${p.src}"><strong>${esc(a.name)}</strong>${p.caption?`<p>${esc(p.caption)}</p>`:""}</div>`})});extras.forEach(e=>{const g=(+e.qty||0)*(+e.sell||0),c=(+e.qty||0)*(+e.cost||0);eg+=g;ec+=c;if(e.show&&g>0)$("cExtras").innerHTML+=`<div class="metric"><span>${esc(e.name)}</span><strong>${eur(g)}</strong></div>`});const total=mg+eg,net=total/1.19,sn=self+ec+C.small+C.fixed;$("totalHz").textContent=hz+" l";$("totalHours").textContent=hours+" Std.";$("measureGross").textContent=eur(mg);$("extraGross").textContent=eur(eg);$("grandGross").textContent=eur(total);$("skontoGross").textContent=eur(total*.95);$("selfNet").textContent=eur(sn);$("marginNet").textContent=eur(net-sn);$("cName").textContent=[$("salutation").value,$("firstName").value,$("lastName").value].filter(Boolean).join(" ")||"–";$("cAddress").textContent=$("objectAddress").value||[$("street").value,$("zip").value,$("city").value].filter(Boolean).join(", ")||"–";$("cDescription").textContent=$("customerDescription").value||"–";$("cPrice").textContent=eur(total);$("cSkonto").textContent=eur(total*.95)}
function cfg(){let url=localStorage.getItem("v6_url")||$("workerUrl").value.trim(),secret=localStorage.getItem("v6_secret")||"";if(url.endsWith("/"))url=url.slice(0,-1);return{url,secret}}
function stat(id,msg,ok){const s=$(id);s.className="status "+(ok?"ok":"err");s.textContent=msg}
async function call(path,opt={}){const c=cfg(),r=await fetch(c.url+path,{...opt,headers:{...(opt.headers||{}),"X-App-Secret":c.secret}}),d=await r.json();if(!r.ok)throw new Error(d.error+(d.details?" – "+JSON.stringify(d.details):""));return d}
$("saveConnection").onclick=()=>{let u=$("workerUrl").value.trim();if(u.endsWith("/"))u=u.slice(0,-1);localStorage.setItem("v6_url",u);localStorage.setItem("v6_secret",$("appSecret").value);stat("settingsStatus","Verbindung wurde auf diesem Gerät gespeichert.",true)};
$("clearConnection").onclick=()=>{localStorage.removeItem("v6_secret");$("appSecret").value="";stat("settingsStatus","APP_SECRET wurde gelöscht.",true)};
$("pdTest").onclick=async()=>{try{await call("/pipedrive/test");stat("pdStatus","Pipedrive-Verbindung erfolgreich.",true)}catch(e){stat("pdStatus",e.message,false)}};
$("pdSearchBtn").onclick=async()=>{const t=$("pdSearch").value.trim();if(t.length<2)return stat("pdStatus","Mindestens 2 Zeichen eingeben.",false);try{const d=await call("/pipedrive/persons/search?term="+encodeURIComponent(t));$("pdResults").innerHTML="";d.people.forEach(p=>{$("pdResults").innerHTML+=`<div class="result"><strong>${esc(p.name)}</strong><p>${esc(p.email||"")} ${esc(p.phone||"")}</p><button class="primary" data-pdid="${p.id}">Übernehmen</button></div>`});document.querySelectorAll("[data-pdid]").forEach(b=>b.onclick=async()=>{try{const d=await call("/pipedrive/persons/"+b.dataset.pdid),p=d.person;$("pipedriveId").value=p.id||"";$("firstName").value=p.firstName||"";$("lastName").value=p.lastName||p.name||"";$("email").value=p.email||"";$("phone").value=p.phone||"";$("street").value=p.street||"";$("zip").value=p.zip||"";$("city").value=p.city||"";$("objectAddress").value=p.objectAddress||"";calc();document.querySelector('[data-page="visit"]').click()}catch(e){stat("pdStatus",e.message,false)}});stat("pdStatus",d.people.length+" Treffer.",true)}catch(e){stat("pdStatus",e.message,false)}};
$("lexTest").onclick=async()=>{try{await call("/profile");stat("lexStatus","Lexware-Verbindung erfolgreich.",true)}catch(e){stat("lexStatus",e.message,false)}};
$("lexSend").onclick=async()=>{try{await call("/contacts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({salutation:$("salutation").value,firstName:$("firstName").value,lastName:$("lastName").value,street:$("street").value,zip:$("zip").value,city:$("city").value,email:$("email").value,phone:$("phone").value,note:"Pipedrive-ID: "+$("pipedriveId").value})});stat("lexStatus","Kunde wurde an Lexware übertragen.",true)}catch(e){stat("lexStatus",e.message,false)}};
$("workerUrl").value=localStorage.getItem("v6_url")||$("workerUrl").value;$("appSecret").value=localStorage.getItem("v6_secret")||"";
renderAreas();renderExtras();bindSpeech();dew();calc();
})();