(function(){"use strict";
const C={spacing:.25,rowSpacing:.25,fHS:14,fFS:10,reserve:.10,hzSell:98,wallSole:300,resin:495,area:690,vat:.19,hourly:85,materialEK:30,drill:60,fill:30,close:40,setupHours:1,small:200,fixed:250};
const $=id=>document.getElementById(id),eur=v=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR"}).format(v),num=v=>new Intl.NumberFormat("de-DE",{maximumFractionDigits:2}).format(v),esc=s=>String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
let measurements=JSON.parse(localStorage.getItem("v51_ms")||"[]"),measures=JSON.parse(localStorage.getItem("v51_m")||"[]"),photos=JSON.parse(localStorage.getItem("v51_p")||"[]"),extras=JSON.parse(localStorage.getItem("v51_e")||"[]");
if(!measurements.length)measurements=[{device:"Gann Hydromette Compact B",value:"",unit:"Digits",location:"",note:""}];
if(!measures.length)measures=[{type:"Horizontalsperre",length:8,width:0,height:0,wall:30,note:""}];
if(!extras.length)extras=[{name:"Baustelleneinrichtung inkl. An- und Abfahrt",qty:1,unit:"pauschal",sell:320.11,cost:269,show:true},{name:"Heizkörper demontieren und montieren",qty:0,unit:"Stück",sell:0,cost:0,show:true},{name:"Bauschutt entsorgen",qty:0,unit:"pauschal",sell:0,cost:0,show:true},{name:"Vorarbeiten / Freilegen",qty:0,unit:"Stunden",sell:0,cost:0,show:true}];

document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));document.querySelectorAll("nav button").forEach(x=>x.classList.remove("active"));$(b.dataset.page).classList.add("active");b.classList.add("active")});
$("gotoPd").onclick=()=>document.querySelector('[data-page="systems"]').click();
$("clearCustomer").onclick=()=>{["salutation","firstName","lastName","phone","email","company","street","zip","city","objectAddress","pipedriveId"].forEach(id=>$(id).value="");calc()};
["salutation","firstName","lastName","phone","email","company","street","zip","city","objectAddress","roomTemp","humidity","surfaceTemp","damageDescription","customerDescription"].forEach(id=>$(id).oninput=calc);
$("roomTemp").oninput=$("humidity").oninput=()=>{dew();calc()};
function dew(){const t=+$("roomTemp").value,rh=+$("humidity").value;if(!Number.isFinite(t)||!rh){$("dewPoint").value="";return}const a=17.62,b=243.12,g=Math.log(rh/100)+a*t/(b+t);$("dewPoint").value=(b*g/(a-g)).toFixed(1)}

function save(){localStorage.setItem("v51_ms",JSON.stringify(measurements));localStorage.setItem("v51_m",JSON.stringify(measures));localStorage.setItem("v51_e",JSON.stringify(extras));try{localStorage.setItem("v51_p",JSON.stringify(photos))}catch(e){}}
function renderMs(){const b=$("measurementList");b.innerHTML="";measurements.forEach((m,i)=>{const d=document.createElement("div");d.className="item";d.innerHTML=`<div class="item-grid"><div class="wide"><label>Gerät</label><input data-mi="${i}" data-mf="device" value="${esc(m.device)}"></div><div><label>Wert</label><input data-mi="${i}" data-mf="value" value="${esc(m.value)}"></div><div><label>Einheit</label><input data-mi="${i}" data-mf="unit" value="${esc(m.unit)}"></div><div><label>Position</label><input data-mi="${i}" data-mf="location" value="${esc(m.location)}"></div><div class="wide"><label>Bemerkung</label><div class="speech-row"><input id="msnote${i}" data-mi="${i}" data-mf="note" value="${esc(m.note)}"><button class="speech" data-speech-target="msnote${i}">🎤</button></div></div><button class="danger" data-md="${i}">Löschen</button></div>`;b.appendChild(d)});
bindFields(b,"mi","mf",measurements,renderMs);b.querySelectorAll("[data-md]").forEach(x=>x.onclick=()=>{measurements.splice(+x.dataset.md,1);renderMs();save()});bindSpeech()}
$("addMeasurement").onclick=()=>{measurements.push({device:"Gann Hydromette Compact B",value:"",unit:"Digits",location:"",note:""});renderMs();save()};

function hs(l,w){const holes=Math.ceil((+l||0)/C.spacing);return{holes,liters:holes*(+w||0)*C.fHS/1000}}
function fs(w,h,t){const hr=Math.ceil((+w||0)/C.spacing),rows=Math.ceil((+h||0)/C.rowSpacing);return{holes:hr*rows,area:(+w||0)*(+h||0),liters:hr*(+t||0)*C.fHS/1000+Math.max(rows-1,0)*hr*(+t||0)*C.fFS/1000}}
function cm(m){let holes=0,liters=0,gross=0,label="",hours=0;if(m.type==="Horizontalsperre"){const r=hs(m.length,m.wall);holes=r.holes;liters=r.liters;gross=Math.ceil(liters*(1+C.reserve))*C.hzSell*(1+C.vat);label=`${num(m.length)} lfm`}if(m.type==="Flächensperre"){const r=fs(m.width,m.height,m.wall);holes=r.holes;liters=r.liters;gross=r.area*C.area;label=`${num(m.width)} × ${num(m.height)} m = ${num(r.area)} m²`}if(m.type==="Harzverpressung"){gross=(+m.length||0)*C.resin;label=`${num(m.length)} lfm`}if(m.type==="Wand-Sohlen-Anschluss"){const r=hs(m.length,m.wall);holes=r.holes;liters=r.liters;gross=(+m.length||0)*C.wallSole+Math.ceil(liters*(1+C.reserve))*C.hzSell*(1+C.vat);label=`${num(m.length)} lfm inkl. HS`}if(holes)hours=Math.ceil(holes/C.drill+holes/C.fill+holes/C.close+C.setupHours);const reserve=Math.ceil(liters*(1+C.reserve)),self=reserve*C.materialEK+hours*C.hourly;return{holes,liters,reserve,gross,label,hours,self}}
function renderMeasures(){const b=$("measureList");b.innerHTML="";measures.forEach((m,i)=>{const ar=m.type==="Flächensperre",d=document.createElement("div");d.className="item";d.innerHTML=`<div class="item-grid"><div class="wide"><label>Maßnahme</label><select data-xi="${i}" data-xf="type"><option ${m.type==="Horizontalsperre"?"selected":""}>Horizontalsperre</option><option ${m.type==="Flächensperre"?"selected":""}>Flächensperre</option><option ${m.type==="Harzverpressung"?"selected":""}>Harzverpressung</option><option ${m.type==="Wand-Sohlen-Anschluss"?"selected":""}>Wand-Sohlen-Anschluss</option></select></div><div><label>Wandstärke cm</label><input data-xi="${i}" data-xf="wall" value="${m.wall}"></div>${ar?`<div><label>Breite m</label><input data-xi="${i}" data-xf="width" value="${m.width}"></div><div><label>Höhe m</label><input data-xi="${i}" data-xf="height" value="${m.height}"></div>`:`<div><label>Länge lfm</label><input data-xi="${i}" data-xf="length" value="${m.length}"></div>`}<div class="wide"><label>Notiz zur Maßnahme</label><div class="speech-row"><input id="mnote${i}" data-xi="${i}" data-xf="note" value="${esc(m.note)}"><button class="speech" data-speech-target="mnote${i}">🎤</button></div></div><button class="danger" data-xd="${i}">Löschen</button></div><div id="mr${i}"></div>`;b.appendChild(d)});
bindFields(b,"xi","xf",measures,renderMeasures);b.querySelectorAll("[data-xd]").forEach(x=>x.onclick=()=>{measures.splice(+x.dataset.xd,1);renderMeasures();renderPhotos();save();calc()});bindSpeech()}
$("addMeasure").onclick=()=>{measures.push({type:"Horizontalsperre",length:0,width:0,height:0,wall:30,note:""});renderMeasures();renderPhotos();save();calc()};

function renderExtras(){const b=$("extraList");b.innerHTML="";extras.forEach((e,i)=>{const d=document.createElement("div");d.className="item";d.innerHTML=`<div class="item-grid"><div class="wide"><label>Leistung</label><input data-ei="${i}" data-ef="name" value="${esc(e.name)}"></div><div><label>Menge</label><input data-ei="${i}" data-ef="qty" value="${e.qty}"></div><div><label>Einheit</label><input data-ei="${i}" data-ef="unit" value="${esc(e.unit)}"></div><div><label>VK brutto</label><input data-ei="${i}" data-ef="sell" value="${e.sell}"></div><div><label>EK netto</label><input data-ei="${i}" data-ef="cost" value="${e.cost}"></div><label><input type="checkbox" data-es="${i}" ${e.show?"checked":""}> Kundenansicht</label><button class="danger" data-ed="${i}">Löschen</button></div>`;b.appendChild(d)});
bindFields(b,"ei","ef",extras,renderExtras);b.querySelectorAll("[data-es]").forEach(x=>x.onchange=()=>{extras[+x.dataset.es].show=x.checked;save();calc()});b.querySelectorAll("[data-ed]").forEach(x=>x.onclick=()=>{extras.splice(+x.dataset.ed,1);renderExtras();save();calc()})}
$("addExtra").onclick=()=>{extras.push({name:"",qty:1,unit:"pauschal",sell:0,cost:0,show:true});renderExtras();save();calc()};

$("photoInput").onchange=e=>{[...e.target.files].forEach(f=>{const r=new FileReader();r.onload=x=>{photos.push({src:x.target.result,measureIndex:0,caption:"",show:true});renderPhotos();save();calc()};r.readAsDataURL(f)});e.target.value=""};
function measureOptions(selected){return measures.map((m,i)=>`<option value="${i}" ${i==selected?"selected":""}>${i+1}. ${esc(m.type)}</option>`).join("")}
function renderPhotos(){const b=$("photoGrid");b.innerHTML="";photos.forEach((p,i)=>{const d=document.createElement("div");d.className="photo-card";d.innerHTML=`<img src="${p.src}"><label>Maßnahme</label><select data-pi="${i}" data-pf="measureIndex">${measureOptions(p.measureIndex)}</select><label>Beschreibung</label><div class="speech-row"><input id="pcap${i}" data-pi="${i}" data-pf="caption" value="${esc(p.caption)}"><button class="speech" data-speech-target="pcap${i}">🎤</button></div><label><input type="checkbox" data-ps="${i}" ${p.show?"checked":""}> Kundenansicht</label><button class="danger" data-pd="${i}">Löschen</button>`;b.appendChild(d)});
bindFields(b,"pi","pf",photos,renderPhotos);b.querySelectorAll("[data-ps]").forEach(x=>x.onchange=()=>{photos[+x.dataset.ps].show=x.checked;save();calc()});b.querySelectorAll("[data-pd]").forEach(x=>x.onclick=()=>{photos.splice(+x.dataset.pd,1);renderPhotos();save();calc()});bindSpeech()}

function bindFields(box,di,df,arr,rerender){box.querySelectorAll(`[data-${df}]`).forEach(x=>x.oninput=()=>{arr[+x.dataset[di]][x.dataset[df]]=x.value;if(x.dataset[df]==="type")rerender();save();calc()})}
function bindSpeech(){document.querySelectorAll("[data-speech-target]").forEach(btn=>btn.onclick=()=>startSpeech(btn.dataset.speechTarget))}
function startSpeech(target){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Spracheingabe wird in diesem Browser nicht unterstützt. Nutze alternativ die Diktierfunktion der iPhone-Tastatur.");return}const r=new SR();r.lang="de-DE";r.interimResults=false;r.onresult=e=>{const el=$(target);el.value=(el.value?el.value+" ":"")+e.results[0][0].transcript;el.dispatchEvent(new Event("input",{bubbles:true}))};r.onerror=()=>alert("Spracheingabe konnte nicht gestartet werden.");r.start()}

function calc(){let mg=0,self=0,hz=0,hours=0,eg=0,ec=0;$("calcMeasures").innerHTML="";$("cMeasures").innerHTML="";$("cExtras").innerHTML="";
measures.forEach((m,i)=>{const r=cm(m);mg+=r.gross;self+=r.self;hz+=r.reserve;hours+=r.hours;const mr=$("mr"+i);if(mr)mr.textContent=`${r.label} · ${r.reserve} l Material · ${r.hours} Std. · ${eur(r.gross)}`;$("calcMeasures").innerHTML+=`<div class="result"><strong>${esc(m.type)}</strong><div class="metric"><span>Umfang</span><strong>${r.label}</strong></div><div class="metric"><span>Material inkl. Reserve</span><strong>${r.reserve} l</strong></div><div class="metric"><span>Arbeitszeit</span><strong>${r.hours} Std.</strong></div><div class="metric"><span>Preis brutto</span><strong>${eur(r.gross)}</strong></div></div>`;$("cMeasures").innerHTML+=`<div class="metric"><span>${esc(m.type)}</span><strong>${r.label}</strong></div>`});
extras.forEach(e=>{const g=(+e.qty||0)*(+e.sell||0),c=(+e.qty||0)*(+e.cost||0);eg+=g;ec+=c;if(e.show&&g>0)$("cExtras").innerHTML+=`<div class="metric"><span>${esc(e.name)}</span><strong>${eur(g)}</strong></div>`});
const total=mg+eg,net=total/(1+C.vat),sn=self+ec+C.small+C.fixed;
$("totalHz").textContent=hz+" l";$("totalHours").textContent=hours+" Std.";$("measureGross").textContent=eur(mg);$("extraGross").textContent=eur(eg);$("grandGross").textContent=eur(total);$("skontoGross").textContent=eur(total*.95);$("selfNet").textContent=eur(sn);$("marginNet").textContent=eur(net-sn);
$("cName").textContent=[$("salutation").value,$("firstName").value,$("lastName").value].filter(Boolean).join(" ")||"–";$("cAddress").textContent=$("objectAddress").value||[$("street").value,$("zip").value,$("city").value].filter(Boolean).join(", ")||"–";$("cDescription").textContent=$("customerDescription").value||"–";$("cPrice").textContent=eur(total);$("cSkonto").textContent=eur(total*.95);$("cPhotos").innerHTML="";photos.filter(p=>p.show).forEach(p=>{const m=measures[+p.measureIndex];$("cPhotos").innerHTML+=`<div class="photo-card"><img src="${p.src}"><strong>${m?esc(m.type):""}</strong>${p.caption?`<p>${esc(p.caption)}</p>`:""}</div>`})}

function cfg(){let url=$("workerUrl").value.trim();if(url.endsWith("/"))url=url.slice(0,-1);const secret=$("appSecret").value;localStorage.setItem("v51_url",url);localStorage.setItem("v51_sec",secret);return{url,secret}}
function stat(id,msg,ok){const s=$(id);s.className="status "+(ok?"ok":"err");s.textContent=msg}
async function call(path,opt={}){const c=cfg(),r=await fetch(c.url+path,{...opt,headers:{...(opt.headers||{}),"X-App-Secret":c.secret}}),d=await r.json();if(!r.ok)throw new Error(d.error+(d.details?" – "+JSON.stringify(d.details):""));return d}
$("pdTest").onclick=async()=>{try{await call("/pipedrive/test");stat("pdStatus","Pipedrive-Verbindung erfolgreich.",true)}catch(e){stat("pdStatus",e.message,false)}};
$("pdSearchBtn").onclick=async()=>{const t=$("pdSearch").value.trim();if(t.length<2)return stat("pdStatus","Mindestens 2 Zeichen eingeben.",false);try{const d=await call("/pipedrive/persons/search?term="+encodeURIComponent(t));renderPd(d.people||[]);stat("pdStatus",(d.people||[]).length+" Treffer.",true)}catch(e){stat("pdStatus",e.message,false)}};
function renderPd(ps){$("pdResults").innerHTML="";ps.forEach(p=>{$("pdResults").innerHTML+=`<div class="result"><strong>${esc(p.name)}</strong><p>${esc(p.email||"")} ${esc(p.phone||"")}</p><button class="primary" data-pdid="${p.id}">Übernehmen</button></div>`});document.querySelectorAll("[data-pdid]").forEach(b=>b.onclick=async()=>{try{const d=await call("/pipedrive/persons/"+b.dataset.pdid);fill(d.person);document.querySelector('[data-page="visit"]').click();stat("pdStatus","Kundendaten übernommen.",true)}catch(e){stat("pdStatus",e.message,false)}})}
function fill(p){$("pipedriveId").value=p.id||"";$("firstName").value=p.firstName||"";$("lastName").value=p.lastName||p.name||"";$("email").value=p.email||"";$("phone").value=p.phone||"";$("street").value=p.street||"";$("zip").value=p.zip||"";$("city").value=p.city||"";$("objectAddress").value=p.objectAddress||"";calc()}
$("lexTest").onclick=async()=>{try{await call("/profile");stat("lexStatus","Lexware-Verbindung erfolgreich.",true)}catch(e){stat("lexStatus",e.message,false)}};
$("lexSend").onclick=async()=>{try{await call("/contacts",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({salutation:$("salutation").value,firstName:$("firstName").value,lastName:$("lastName").value,street:$("street").value,zip:$("zip").value,city:$("city").value,email:$("email").value,phone:$("phone").value,note:"Pipedrive-ID: "+$("pipedriveId").value})});stat("lexStatus","Kunde an Lexware übertragen.",true)}catch(e){stat("lexStatus",e.message,false)}};

$("workerUrl").value=localStorage.getItem("v51_url")||$("workerUrl").value;$("appSecret").value=localStorage.getItem("v51_sec")||"";
renderMs();renderMeasures();renderExtras();renderPhotos();bindSpeech();dew();calc();
})();